CREATE TABLE "C##AND"."PRODUTOS" 
   (	"ID_PRODUTO" NUMBER(*,0), 
	"NOME" VARCHAR2(100 BYTE), 
	"DESCRICAO" CLOB, 
	"PRECO" NUMBER(10,2), 
	"QUANTIDADE_ESTOQUE" NUMBER(*,0) DEFAULT 0, 
	"ID_CATEGORIA" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("DESCRICAO") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
REM INSERTING into C##AND.PRODUTOS
SET DEFINE OFF;
Insert into C##AND.PRODUTOS (ID_PRODUTO,NOME,PRECO,QUANTIDADE_ESTOQUE,ID_CATEGORIA) values ('123','Miojo','2,99','15','2');
Insert into C##AND.PRODUTOS (ID_PRODUTO,NOME,PRECO,QUANTIDADE_ESTOQUE,ID_CATEGORIA) values ('122','Bateria','25','10','1');


  CREATE UNIQUE INDEX "C##AND"."SYS_C0014393" ON "C##AND"."PRODUTOS" ("ID_PRODUTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##AND"."BI_PRODUTOS" 
BEFORE INSERT ON produtos
FOR EACH ROW
BEGIN
  IF :NEW.id_produto IS NULL THEN
    :NEW.id_produto := SEQ_PRODUTOS.NEXTVAL;
  END IF;
END;

/
ALTER TRIGGER "C##AND"."BI_PRODUTOS" ENABLE;

  ALTER TABLE "C##AND"."PRODUTOS" MODIFY ("NOME" NOT NULL ENABLE);
  ALTER TABLE "C##AND"."PRODUTOS" MODIFY ("ID_CATEGORIA" NOT NULL ENABLE);
  ALTER TABLE "C##AND"."PRODUTOS" ADD CHECK (preco >= 0) ENABLE;
  ALTER TABLE "C##AND"."PRODUTOS" ADD CHECK (quantidade_estoque >= 0) ENABLE;
  ALTER TABLE "C##AND"."PRODUTOS" ADD PRIMARY KEY ("ID_PRODUTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;

  ALTER TABLE "C##AND"."PRODUTOS" ADD FOREIGN KEY ("ID_CATEGORIA")
	  REFERENCES "C##AND"."CATEGORIAS" ("ID_CATEGORIA") ENABLE;


  CREATE TABLE "C##AND"."CATEGORIAS" 
   (	"ID_CATEGORIA" NUMBER(*,0), 
	"NOME" VARCHAR2(100 BYTE), 
	"DESCRICAO" CLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("DESCRICAO") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
REM INSERTING into C##AND.CATEGORIAS
SET DEFINE OFF;
Insert into C##AND.CATEGORIAS (ID_CATEGORIA,NOME) values ('2','Alimentos');
Insert into C##AND.CATEGORIAS (ID_CATEGORIA,NOME) values ('1','Eletr�nicos');
Insert into C##AND.CATEGORIAS (ID_CATEGORIA,NOME) values ('21','Inform�tica');

  CREATE UNIQUE INDEX "C##AND"."SYS_C0014387" ON "C##AND"."CATEGORIAS" ("ID_CATEGORIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE UNIQUE INDEX "C##AND"."SYS_C0014388" ON "C##AND"."CATEGORIAS" ("NOME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##AND"."TRG_CATEGORIAS_BI" 
BEFORE INSERT ON categorias
FOR EACH ROW
 WHEN (NEW.id_categoria IS NULL) BEGIN
  SELECT seq_categorias.NEXTVAL INTO :NEW.id_categoria FROM dual;
END;
/
ALTER TRIGGER "C##AND"."TRG_CATEGORIAS_BI" ENABLE;

  ALTER TABLE "C##AND"."CATEGORIAS" MODIFY ("NOME" NOT NULL ENABLE);
  ALTER TABLE "C##AND"."CATEGORIAS" ADD PRIMARY KEY ("ID_CATEGORIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##AND"."CATEGORIAS" ADD UNIQUE ("NOME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
